module.exports = [
    'iphone 12 pro',
    'iphone 13 pro',
    'samsung galaxy s22',
    'google pixel 6',
    'oneplus 9 pro',
    'xiaomi mi 11 ultra',
    'oppo find x3 pro',
    'huawei p40 pro',
    'sony xperia 1 iv',
    'lg g8x thinq',
    'redmi poco',
    'realme gt 2 pro',
    'nokia 8.3 5g',
    'motorola razr',
    'asus zenfone 8',
    'htc u20 5g',
    'vivo x60 pro',
    'meizu 18 pro',
    'zte axon 30 ultra',
    'honor 50 pro',
    'google pixel 5a',
    'samsung galaxy s21 fe',
    'oneplus 9rt',
    'xiaomi mi 11t pro',
    'oppo find x5 pro',
    'huawei p50 pro',
]