[
    {
        _events: [Object: null prototype] {
        error: [Function: noop],
        newuser: [AsyncFunction(anonymous)],
        newmessage: [Function(anonymous)]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    nsp: Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Server],
        name: '/',
        adapter: [Adapter],
        [Symbol(kCapture)]: false
    },
    client: Client {
        sockets: [Map],
        nsps: [Map],
        server: [Server],
        conn: [Socket],
        encoder: [Encoder],
        decoder: [Decoder],
        id: '0XVSTzW8wT_ZwdZEAAAA',
        onclose: [Function: bound onclose],
        ondata: [Function: bound ondata],
        onerror: [Function: bound onerror],
        ondecoded: [Function: bound ondecoded],
        connectTimeout: undefined
    },
    recovered: false,
    data: {},
    connected: true,
    acks: Map(0) {},
    fns: [],
    flags: {},
    server: Server {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _nsps: [Map],
    parentNsps: Map(0) {},
    parentNamespacesFromRegExp: Map(0) {},
    _path: '/socket.io',
    clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
    _connectTimeout: 45000,
    _serveClient: true,
    _parser: [Object],
    encoder: [Encoder],
    opts: [Object],
    _adapter: [class Adapter extends EventEmitter],
    sockets: [Namespace],
    eio: [Server],
    httpServer: [Server],
    engine: [Server],
    [Symbol(kCapture)]: false
      },
    adapter: Adapter {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    nsp: [Namespace],
    rooms: [Map],
    sids: [Map],
    encoder: [Encoder],
    [Symbol(kCapture)]: false
      },
    id: 'sWmJcOva-HI2_vktAAAB',
    handshake: {
        headers: [Object],
        time: 'Mon May 27 2024 20:01:46 GMT+0530 (India Standard Time)',
        address: '::1',
        xdomain: false,
        secure: false,
        issued: 1716820306862,
        url: '/socket.io/?EIO=4&transport=polling&t=O-wTkkI',
        query: [Object: null prototype],
        auth: {}
    },
    [Symbol(kCapture)]: false
    },
    Socket {
        _events: [Object: null prototype] {
        error: [Function: noop],
        newuser: [AsyncFunction(anonymous)],
        newmessage: [Function(anonymous)]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    nsp: Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Server],
        name: '/',
        adapter: [Adapter],
        [Symbol(kCapture)]: false
    },
    client: Client {
        sockets: [Map],
        nsps: [Map],
        server: [Server],
        conn: [Socket],
        encoder: [Encoder],
        decoder: [Decoder],
        id: 'TdLNc8QQ7oRDI8CaAAAC',
        onclose: [Function: bound onclose],
        ondata: [Function: bound ondata],
        onerror: [Function: bound onerror],
        ondecoded: [Function: bound ondecoded],
        connectTimeout: undefined
    },
    recovered: false,
    data: {},
    connected: true,
    acks: Map(0) {},
    fns: [],
    flags: {},
    server: Server {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _nsps: [Map],
    parentNsps: Map(0) {},
    parentNamespacesFromRegExp: Map(0) {},
    _path: '/socket.io',
    clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
    _connectTimeout: 45000,
    _serveClient: true,
    _parser: [Object],
    encoder: [Encoder],
    opts: [Object],
    _adapter: [class Adapter extends EventEmitter],
    sockets: [Namespace],
    eio: [Server],
    httpServer: [Server],
    engine: [Server],
    [Symbol(kCapture)]: false
      },
    adapter: Adapter {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    nsp: [Namespace],
    rooms: [Map],
    sids: [Map],
    encoder: [Encoder],
    [Symbol(kCapture)]: false
      },
    id: 'XsTOEGnC98N1I-QLAAAE',
    handshake: {
        headers: [Object],
        time: 'Mon May 27 2024 20:01:47 GMT+0530 (India Standard Time)',
        address: '::1',
        xdomain: false,
        secure: false,
        issued: 1716820307388,
        url: '/socket.io/?EIO=4&transport=polling&t=O-wTksp',
        query: [Object: null prototype],
        auth: {}
    },
    [Symbol(kCapture)]: false
    },
    Socket {
        _events: [Object: null prototype] {
        error: [Function: noop],
        newuser: [AsyncFunction(anonymous)],
        newmessage: [Function(anonymous)]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    nsp: Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Server],
        name: '/',
        adapter: [Adapter],
        [Symbol(kCapture)]: false
    },
    client: Client {
        sockets: [Map],
        nsps: [Map],
        server: [Server],
        conn: [Socket],
        encoder: [Encoder],
        decoder: [Decoder],
        id: 's9IJQKDp-WCgqvwhAAAG',
        onclose: [Function: bound onclose],
        ondata: [Function: bound ondata],
        onerror: [Function: bound onerror],
        ondecoded: [Function: bound ondecoded],
        connectTimeout: undefined
    },
    recovered: false,
    data: {},
    connected: true,
    acks: Map(0) {},
    fns: [],
    flags: {},
    server: Server {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _nsps: [Map],
    parentNsps: Map(0) {},
    parentNamespacesFromRegExp: Map(0) {},
    _path: '/socket.io',
    clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
    _connectTimeout: 45000,
    _serveClient: true,
    _parser: [Object],
    encoder: [Encoder],
    opts: [Object],
    _adapter: [class Adapter extends EventEmitter],
    sockets: [Namespace],
    eio: [Server],
    httpServer: [Server],
    engine: [Server],
    [Symbol(kCapture)]: false
      },
    adapter: Adapter {
        _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    nsp: [Namespace],
    rooms: [Map],
    sids: [Map],
    encoder: [Encoder],
    [Symbol(kCapture)]: false
      },
    id: 'waDVdqEzjAzq3_MvAAAH',
    handshake: {
        headers: [Object],
        time: 'Mon May 27 2024 20:01:47 GMT+0530 (India Standard Time)',
        address: '::1',
        xdomain: false,
        secure: false,
        issued: 1716820307847,
        url: '/socket.io/?EIO=4&transport=polling&t=O-wTky8',
        query: [Object: null prototype],
        auth: {}
    },
    [Symbol(kCapture)]: false
    }]